name: text_field_custom
description: In this package I have customized the textformfield for easy use.
version: 0.0.2
repository: https://github.com/harshitAmar/text_field_custom.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  validation_helper: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
